### ISSUE TITLE
Startup error : Storage provider type (Netherite) was not found

### ISSUE THREAD

**Issue by DEndersby91** [microsoft/durabletask-netherite#350] opened 2024-02-13 22:24 UTC
Hi, Sorry this question is a bit basic compared to the others.
I've been trying to setup Netherite in my DF projects following the guides found here:
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/quickstart-netherite
- https://microsoft.github.io/durabletask-netherite/#/?id=getting-started

My projects are .Net8, functions V4, runtime dotnet-isolated with all latest packages.
Due to this I've preferred the first guide as it directly references dotnet-isolated setups.
I've : 
- Added Nuget Package : Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite , latest version 1.4.1
- Set host.json extensions->durableTask->storageProvider->type = "Netherite" , with and without additional configs mentioned in second guide
- Set local.settings.json AzureWebJobsStorage and EventHubsConnection to "UseDevelopmentStorage=true" and "SingleHost"

When I attempt to run my application (Windows and Mac) with these changes I get the error :
 ```
A host error has occurred during startup operation '4eb3474a-3a8b-4a1c-afed-3cffb1655c3c'.
Microsoft.Azure.WebJobs.Extensions.DurableTask: Storage provider type (Netherite) was not found. Available storage providers: AzureStorage. System.Linq: Sequence contains no matching element.
Value cannot be null. (Parameter 'provider')
```

Reverting these changes and defaulting back to AzureStorage allows my projects to run again. 
Are you able to make any recommendations and/or confirm .Net 8 Isolated is supported by Netherite.
Am I missing something required in order for this extension to be picked up?

Thanks for your time.

**Comment by cgillum** [comment] 2024-02-14 01:01
I believe this configuration should be supported. @sebastianburckhardt or @davidmrdavid, can either of you confirm?

@DEndersby91 when building your Function app locally on Windows, do you see a `[project-root]\bin\Debug\net8.0\.azurefunctions\Microsoft.Azure.WebJobs.Extensions.DurableTask.Netherite.dll` file?

**Comment by DEndersby91** [comment] 2024-02-14 09:36
Hi @cgillum.

On Windows the "Microsoft.Azure.WebJobs.Extensions.DurableTask.Netherite.dll" is NOT in the ".azurefunctions" folder but is in it's parent "net8.0" folder.
I was hoping that was going to be the issue but copying the dll into the ".azurefunctions" folder but sadly that did not fix the issue.

On Mac there is no ".azurefunctions" folder in the ".net8.0" folder but the dlls are in the ".net8.0" folder, the same as Windows.

**Comment by mikegoatly** [comment] 2024-02-16 07:32
@DEndersby91 are you running v1.17.0 of Microsoft.Azure.Functions.Worker.Sdk? If so, please could you try rolling that back to v1.16.4?

**Comment by DEndersby91** [comment] 2024-02-18 11:49
@mikegoatly sorry for my delay. I can confirm using 1.16.4 of the Worker.Sdk works with Netherite. Thanks for that work around, I'm happy to proceed with this unless there are any gotchas I should know about. 

Is the underlying issue with Netherite or the Worker.Sdk? If the latter would you like me a re-raise this issue in the correct repo?

**Comment by mikegoatly** [comment] 2024-02-19 12:18
@DEndersby91 I thought it worth checking because I've a support case open at the moment and ran into this exact issue with the SQL provider after upgrading to v1.17.0. I don't work for Microsoft, but I suspect that someone there could migrate this issue across to Worker.Sdk if needed.

**Comment by LockTar** [comment] 2024-02-27 20:13
@mikegoatly I can confirm that rolling back to v1.16.4 of the Worker.Sdk works for the SQL provider.

I have a brand new Azure Function Isolated v4 .NET 8 project. I updated all packages to the latest version when I installed the SQL provider (following MS documentation). After starting I got the following error:

`A host error has occurred during startup operation '90a8fdcc-0ba2-43cc-9906-110b9b994f22'.
Microsoft.Azure.WebJobs.Extensions.DurableTask: Storage provider type (mssql) was not found. Available storage providers: AzureStorage. System.Linq: Sequence contains no matching element.
Value cannot be null. (Parameter 'provider')`

I'm already busy for hours trying to understand why it isn't working. I finally found this issue and after rolling back of the worker it immediately worked!

Thank you!

**Comment by mikegoatly** [comment] 2024-02-28 11:20
@cgillum somethings definitely up with at least the Netherite and SQL Server durable tasks providers when people upgrade to v1.17.0 of Microsoft.Azure.Functions.Worker.Sdk. I've got a environment configured in this state and am very happy to help test things further if needed - case number is 2401120050004037.

**Comment by cgillum** [comment] 2024-02-28 18:28
@mikegoatly I can confirm in my own local environment that the alternate Durable Task backend assemblies are not being loaded in the v1.17.0 version of Microsoft.Azure.Functions.Worker.Sdk. I assume this must be some regression in the SDK.

I've opened the following issue in the Azure Functions .NET Isolated Worker repo: https://github.com/Azure/azure-functions-dotnet-worker/issues/2307. This appears to be a regression, and I noticed there are many other reports of problems with this extension version as well (perhaps they are all related).

**Comment by mikegoatly** [comment] 2024-02-28 18:34
Thanks @cgillum, much appreciated

**Comment by lilyjma** [comment] 2024-02-29 18:27
Hi all, v1.17.1 of Microsoft.Azure.Functions.Worker.Sdk has been deployed and should address the known issues! Thanks.

**Comment by mikegoatly** [comment] 2024-03-01 08:27
@lilyjma I've tried updating to v1.17.1, but I'm still seeing the same issue

**Comment by LockTar** [comment] 2024-03-01 08:34
> Hi all, v1.17.1 of Microsoft.Azure.Functions.Worker.Sdk has been deployed and should address the known issues! Thanks.

If I update, I still have the same problem with the SQL provider. This is not resolved in v1.17.1.

**Comment by cgillum** [comment] 2024-03-01 17:55
Adding @kshyju, who is investigating the issues with Microsoft.Azure.Functions.Worker.Sdk.

**Comment by kshyju** [comment] 2024-03-01 23:18
@DEndersby91 This was caused by a regression in Microsoft.Azure.Functions.Worker.Sdk 1.17.0. We released a new version, 1.17.2 which includes a fix for this issue.

https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.17.2

Could you try that version and let us know how that goes? 

Thanks for your patience.

**Comment by mikegoatly** [comment] 2024-03-01 23:41
@kshyju I've updated to 1.17.2 and it looks good so far to me.

**Comment by cgillum** [comment] 2024-03-02 01:18
I verified that it's working in my case too. Closing this for now since I think the problem is resolved with 1.17.2 (let us know @DEndersby91 if you're still running into problems).

**Closed by cgillum** 2024-03-02 01:18 UTC
Labels: needs author response, Needs: Triage :mag:

**Comment by LockTar** [comment] 2024-03-04 13:29
I can confirm that version 1.17.2 fixes it for the SQL provider too!

**Comment by DEndersby91** [comment] 2024-03-04 13:32
Thanks to everyone involved with resolving this.
