### ISSUE TITLE
Custom orchestration status support

### ISSUE THREAD

**Issue by somaka** [microsoft/durabletask-netherite#67] opened 2021-07-28 09:46 UTC
It doesn't seem like context.df.setCustomStatus works - at least the HTTP orchestration API doesn't return anything after attempting to set the status.

This is quite an important feature for the interactive scenarios - is it planned to be supported?

Could be a platform support issue also, I tried using it with Node.js, maybe it actually works with C#?

**Comment by sebastianburckhardt** [comment] 2021-07-29 13:16
Custom orchestration status is definitely supported.

I just tested it on C# and it works correctly, so perhaps there is some problem specific to the Node.js platform.

Does the same scenario work when using the the default AzureStorage backend?

**Comment by somaka** [comment] 2021-07-29 13:23
Yes, it works as expected with the Azure Storage but changing to Netherite causes custom statuses to disappear.

 

So yes, must be Node.js specific implementation issue then.

**Comment by sebastianburckhardt** [comment] 2021-09-14 22:59
Sorry for the long delay. 

I believe this may be a duplicate of bug #69 which essentially made orchestrations not work at all.
I just tested it with the workaround in #69 and it seems to work.

**Closed** 2021-12-09 14:56 UTC
Labels: needs author response
