### ISSUE TITLE
Partitions become unresponsive

### ISSUE THREAD

**Issue by alexjebens** [microsoft/durabletask-netherite#342] opened 2024-01-17 12:18 UTC
We are frequently seeing some of our partitions becoming unresponsive in the partitions table.

The partition seems unable to start. Deleting the partitions eventhub resolves the problem but all pending messages are lost, which is not acceptable for this application.

Microsoft.Azure.DurableTask.Netherite.AzureFunctions: 1.4.1
Microsoft.Azure.Webjobs.Extensions.FurableTask: 2.13.0
Microsoft.NET.Sdk.Functions: 4.2.0

Hosting: EP2 with scaling to 2

@sebastianburckhardt I sent you an email with details on the function.

**Comment by alexjebens** [comment] 2024-01-17 12:19
I have a theory: is it possible that the eh-checkpoints become desynchronized from the FASTER storage state? Would it then not be possible to implement a checkpoint provider that utilises FASTER.

**Comment by alexjebens** [comment] 2024-01-24 14:00
I have an exception:

  An attempt was made to move the position before the beginning of the stream.

at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at FASTER.core.GenericAllocator`2.Deserialize(Byte* raw, Int64 ptr, Int64 untilptr, Record`2[] src, Stream stream)
   at FASTER.core.GenericAllocator`2.AsyncReadPageWithObjectsCallback[TContext](UInt32 errorCode, UInt32 numBytes, Object context)
   at DurableTask.Netherite.Faster.AzureStorageDevice.<>c__DisplayClass36_0.<ReadAsync>b__0(Task t) in C:\Users\A60800\src\durabletask-netherite\src\DurableTask.Netherite\StorageLayer\Faster\AzureBlobs\AzureStorageDevice.cs:line 399
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by alexjebens** [comment] 2024-01-24 15:19
This is not resolved when integrating the changes in FASTER.core from #343

**Comment by alexjebens** [comment] 2024-01-24 15:54
It is specifically this [line](https://github.com/microsoft/FASTER/blob/8f69ceb2ec01924c0ab17539fa41b804d6bfe445/cs/src/core/Allocator/GenericAllocator.cs#L821) in FASTER.core

**Comment by alexjebens** [comment] 2024-02-05 10:53
Manually updating to FASTER.core 2.0.23 did not prevent further corruption

**Comment by sebastianburckhardt** [comment] 2024-03-05 18:10
Thanks for reporting this. We are currently suspecting that this corruption is caused by a bug that was fixed in the latest FASTER. Therefore we are now prioritizing updating Netherite to use the latest FASTER version. This work is tracked here: https://github.com/microsoft/durabletask-netherite/pull/344.

**Comment by sebastianburckhardt** [comment] 2024-04-23 21:32
We have released 1.5.0 which contains a much newer version of FASTER, which we think will fix the corruption of FASTER object files. Let us know if you still see these symptoms with version 1.5.0.

**Closed by sebastianburckhardt** 2024-04-23 21:32 UTC
Labels: bug, P1
